-- v6.9 compatibility: restore gateway_outage_events expected by fleet offline-events runtime
CREATE TABLE IF NOT EXISTS public.gateway_outage_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_id character varying(50) NOT NULL REFERENCES public.gateways(gateway_id),
    org_id character varying(50) NOT NULL REFERENCES public.organizations(org_id),
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE IF EXISTS public.gateway_outage_events OWNER TO postgres;

CREATE INDEX IF NOT EXISTS idx_goe_gateway_started
  ON public.gateway_outage_events (gateway_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_goe_org_started
  ON public.gateway_outage_events (org_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_goe_open
  ON public.gateway_outage_events (gateway_id)
  WHERE ended_at IS NULL;

GRANT SELECT, INSERT, UPDATE ON public.gateway_outage_events TO solfacil_app;
GRANT SELECT, INSERT, UPDATE ON public.gateway_outage_events TO solfacil_service;
GRANT USAGE, SELECT ON SEQUENCE public.gateway_outage_events_id_seq TO solfacil_app;
GRANT USAGE, SELECT ON SEQUENCE public.gateway_outage_events_id_seq TO solfacil_service;
